### ISSUE TITLE
autorotation fix

### ISSUE THREAD

**Issue by aiden09** [xen0n/android_vendor_meizu_arale#6]
in framework-base-mtk-core-res-res-values-config.xml in line
 <bool name="config_useSystemClockforRotationSensor">false</bool>
replace "false" with "true". It will be fix unworking autorotation after locked phone. Official CM framework-base have this patch

**Comment by xen0n** [comment]
Oh, I didn't even notice the issue on my Meizu MX4... will test shortly.

**Comment by aiden09** [comment]
it will be stop rotate screen after several times lock/unlock phone. also YT and other flash video do not playback. i fixed it by changing media codes. i do not know how to send it  for you. but 60fps still doesnt not playback.  but i think its bug all CM.it freezing during playback but sound continue playback.

**Comment by xen0n** [comment]
I confirmed the bug and have incorporated an identical fix from @fire855's device tree. Thanks!

As for your patch, feel free to post a gist or just describe it. Someone else has also noticed the YouTube bug but I haven't got time to properly look into it.
